#!/bin/sh
compare=$(which md5)
if [ ! "${compare}" ] ; then
    compare=$(which md5sum)
    if [ ! "${compare}" ] ; then
        echo "Need md5 or md5sum to compare. File a bug"
        exit 1
    fi
fi
PK=${PK-'../../src/pk'}
cd $(dirname $0)
for i in $(find . -name "*.cmd" -print | sort)
do
    base=$(basename $i .cmd)
    got=$(. $i < ${base}.in | ${compare})
    want=$(cat ${base}.out | ${compare})
    if [ "${want}" != "${got}" ]
    then
        echo FAILURE: ${base}
        cat ${base}.cmd
        . $i < ${base}.in
        exit 1
    else
        echo SUCCESS: ${base}
    fi
done
